from pydantic import BaseModel, Field
from lancedb.pydantic import LanceModel, Vector
from dotenv import load_dotenv

load_dotenv()

EMBEDDING_DIM = 768

class Transcript(LanceModel):
    video_id: str = Field(description="ID based on the filename, without extension")
    title: str = Field(description="Readable name of transcript")
    text: str = Field(description="Raw transcript text")
    embedding: Vector(EMBEDDING_DIM)


class Prompt(BaseModel):
    prompt: str = Field(description="Prompt from user, if empty consider it as missing")


class Source(BaseModel):
    video_id: str = Field(description="ID based on filename, without extension")
    title: str = Field(description="Readable name of the transcript")
    score: float | None = Field(
        default=None, description="Similarity score from vector search"
    )


class RagResponse(BaseModel):
    answer: str = Field(
        description="Answer generated by the LLM based on retrieved transcripts")
    sources: list[Source] = Field(
        default_factory=list,
        description="Information about which transcripts were used")
